# Generated by Django 3.0.8 on 2020-08-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrequest',
            name='num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='homerequest',
            name='num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
